services:
  steamroller:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: steamroller
    ports:
      - "8092:8092"
    environment:
      PORT: 8092
    restart: unless-stopped
